### ISSUE TITLE
Error en ejercicio 8.4

### ISSUE THREAD

**Issue by Rai1502** [ArisGuimera/EjerciciosLibroAndroid#3]
Hola amigo, recien ando estudiando y aprendiendo con tu libro.
En el ejercicio o ejemplo 8.4 (de los intents) que debe retornar el nombre. Tengo el codigo y todo exactamente como tu ejemplo solo que al probar la app se cierra repentinamente, podrías ayudarme a saber porque sucede eso?

**Comment by Rai1502** [comment]
Listo, pude resolverlo habia pasado por alto el registrar en el manifiest la actividad. =D

**Comment by ArisGuimera** [comment]
Me alegro que lo hayas solucionado. Cualquier duda me preguntas por aquí o por mis redes sociales :)On 1 Sep 2020 22:03, Rai1502 <notifications@github.com> wrote:
Listo, pude resolverlo habia pasado por alto el registrar en el manifiest la actividad. =D
